name: Continue Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  continue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Continue Action
        uses: forsythetony/continue_action@1.0
        # with:
        # Add any required inputs for continue_action here
        # For example:
        # token: ${{ secrets.GITHUB_TOKEN }}
